
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetMessageModelBlockList {
/*
{
  "id": 1
} 
*/

  int? id;

  GetMessageModelBlockList({
    this.id,
  });
  GetMessageModelBlockList.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    return data;
  }
}

class GetMessageModelData {
/*
{
  "user_name": "Muhammad ibraheem",
  "created_at": "2022-04-22T06:39:51.000Z",
  "image": "https://server.appsstaging.com/3048/edut/public/images/1650541810.jpg",
  "id": 49,
  "sender_id": 23,
  "reciever_id": null,
  "message": "gg",
  "updated_at": null
} 
*/

  String? userName;
  String? createdAt;
  String? image;
  int? id;
  int? senderId;
  String? recieverId;
  String? message;
  String? updatedAt;

  GetMessageModelData({
    this.userName,
    this.createdAt,
    this.image,
    this.id,
    this.senderId,
    this.recieverId,
    this.message,
    this.updatedAt,
  });
  GetMessageModelData.fromJson(Map<String, dynamic> json) {
    userName = json['user_name']?.toString();
    createdAt = json['created_at']?.toString();
    image = json['image']?.toString();
    id = json['id']?.toInt();
    senderId = json['sender_id']?.toInt();
    recieverId = json['reciever_id']?.toString();
    message = json['message']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_name'] = userName;
    data['created_at'] = createdAt;
    data['image'] = image;
    data['id'] = id;
    data['sender_id'] = senderId;
    data['reciever_id'] = recieverId;
    data['message'] = message;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class GetMessageModel {
/*
{
  "object_type": "send_location",
  "data": [
    {
      "user_name": "Muhammad ibraheem",
      "created_at": "2022-04-22T06:39:51.000Z",
      "image": "https://server.appsstaging.com/3048/edut/public/images/1650541810.jpg",
      "id": 49,
      "sender_id": 23,
      "reciever_id": null,
      "message": "gg",
      "updated_at": null
    }
  ],
  "block_list": [
    {
      "id": 1
    }
  ]
} 
*/

  String? objectType;
  List<GetMessageModelData?>? data;
  List<GetMessageModelBlockList?>? blockList;

  GetMessageModel({
    this.objectType,
    this.data,
    this.blockList,
  });
  GetMessageModel.fromJson(Map<String, dynamic> json) {
    objectType = json['object_type']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <GetMessageModelData>[];
      v.forEach((v) {
        arr0.add(GetMessageModelData.fromJson(v));
      });
      this.data = arr0;
    }
    if (json['block_list'] != null) {
      final v = json['block_list'];
      final arr0 = <GetMessageModelBlockList>[];
      v.forEach((v) {
        arr0.add(GetMessageModelBlockList.fromJson(v));
      });
      blockList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['object_type'] = objectType;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    if (blockList != null) {
      final v = blockList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['block_list'] = arr0;
    }
    return data;
  }
}
/*
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetMessageModelData {
/*
{
  "user_name": "fdfds",
  "image": "https://server.appsstaging.com/3048/mao/mao/public/uploads/dfd",
  "id": 1,
  "sender_id": 1,
  "message": "test"
} 
*/

  String? userName;
  String? image;
  int? id;
  int? senderId;
  String? message;

  GetMessageModelData({
    this.userName,
    this.image,
    this.id,
    this.senderId,
    this.message,
  });
  GetMessageModelData.fromJson(Map<String, dynamic> json) {
    userName = json['user_name']?.toString();
    image = json['image']?.toString();
    id = json['id']?.toInt();
    senderId = json['sender_id']?.toInt();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_name'] = userName;
    data['image'] = image;
    data['id'] = id;
    data['sender_id'] = senderId;
    data['message'] = message;
    return data;
  }
}

class GetMessageModel {
/*
{
  "object_type": "get_messages",
  "data": [
    {
      "user_name": "fdfds",
      "image": "https://server.appsstaging.com/3048/mao/mao/public/uploads/dfd",
      "id": 1,
      "sender_id": 1,
      "message": "test"
    }
  ]
} 
*/

  String? objectType;
  List<GetMessageModelData?>? data;

  GetMessageModel({
    this.objectType,
    this.data,
  });
  GetMessageModel.fromJson(Map<String, dynamic> json) {
    objectType = json['object_type']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <GetMessageModelData>[];
      v.forEach((v) {
        arr0.add(GetMessageModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['object_type'] = objectType;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}



// class GetMessageModel {
//   GetMessageModel({
//     required this.objectType,
//     required this.data,
//   });
//   late final String objectType;
//   late final List<ReceiveData> data;

//   GetMessageModel.fromJson(Map<String, dynamic> json) {
//     objectType = json['object_type'];
//     data = List.from(json['data']).map((e) => ReceiveData.fromJson(e)).toList();
//   }

//   Map<String, dynamic> toJson() {
//     final _data = <String, dynamic>{};
//     _data['object_type'] = objectType;
//     _data['data'] = data.map((e) => e.toJson()).toList();
//     return _data;
//   }
// }

// class ReceiveData {
//   ReceiveData({
//     this.userName,
//     this.image,
//     this.id,
//     this.senderId,
//     this.message,
//   });
//   final String? userName;
//   final String? image;
//   final int? id;
//   final int? senderId;
//   final String? message;

//   ReceiveData.fromJson(Map<String, dynamic> json) {
//     userName : json['user_name'];
//     image : json['image'];
//     id : json['id'];
//     senderId: json['sender_id'];
//     message : json['message'];
//   }

//   Map<String, dynamic> toJson() {
//     final _data = <String, dynamic>{};
//     _data['user_name'] = userName;
//     _data['image'] = image;
//     _data['id'] = id;
//     _data['sender_id'] = senderId;
//     _data['message'] = message;
//     return _data;
//   }
// }
*/