class EnentNotificationModel {
  final int? status;
  final List<Data>? data;

  EnentNotificationModel({
    this.status,
    this.data,
  });

  EnentNotificationModel.fromJson(Map<String, dynamic> json)
      : status = json['status'] as int?,
        data = (json['data'] as List?)
            ?.map((dynamic e) => Data.fromJson(e as Map<String, dynamic>))
            .toList();

  Map<String, dynamic> toJson() =>
      {'status': status, 'data': data?.map((e) => e.toJson()).toList()};
}

class Data {
  final int? id;
  final int? senderId;
  final int? recieverId;
  final NData? data;
  final String? type;
  final String? createdAt;
  final String? updatedAt;

  Data({
    this.id,
    this.senderId,
    this.recieverId,
    this.data,
    this.type,
    this.createdAt,
    this.updatedAt,
  });

  Data.fromJson(Map<String, dynamic> json)
      : id = json['id'] as int?,
        senderId = json['sender_id'] as int?,
        recieverId = json['reciever_id'] as int?,
        data = (json['data'] as Map<String, dynamic>?) != null
            ? NData.fromJson(json['data'] as Map<String, dynamic>)
            : null,
        type = json['type'] as String?,
        createdAt = json['created_at'] as String?,
        updatedAt = json['updated_at'] as String?;

  Map<String, dynamic> toJson() => {
        'id': id,
        'sender_id': senderId,
        'reciever_id': recieverId,
        'data': data?.toJson(),
        'type': type,
        'created_at': createdAt,
        'updated_at': updatedAt
      };
}

class NData {
  final String? title;
  final String? description;
  final String? eventDate;
  final String? image;

  NData({
    this.title,
    this.description,
    this.eventDate,
    this.image,
  });

  NData.fromJson(Map<String, dynamic> json)
      : title = json['title'] as String?,
        description = json['description'] as String?,
        eventDate = json['event_date'] as String?,
        image = json['image'] as String?;

  Map<String, dynamic> toJson() => {
        'title': title,
        'description': description,
        'event_date': eventDate,
        'image': image
      };
}
/*
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotificationModelDataDataSub {
/*
{
  "title": "Sydney Hurst",
  "date": "1977-10-22",
  "time": "23:22:00"
} 
*/

  String? title;
  String? date;
  String? time;

  NotificationModelDataDataSub({
    this.title,
    this.date,
    this.time,
  });
  NotificationModelDataDataSub.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    date = json['date']?.toString();
    time = json['time']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['date'] = date;
    data['time'] = time;
    return data;
  }
}

class NotificationModelDataDataImages {
/*
{
  "id": 13,
  "url": "https://server.appsstaging.com/3048/mao/mao/public/uploads/6259367672e50.jpg"
} 
*/

  int? id;
  String? url;

  NotificationModelDataDataImages({
    this.id,
    this.url,
  });
  NotificationModelDataDataImages.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['url'] = url;
    return data;
  }
}

class NotificationModelDataData {
/*
{
  "id": 16,
  "title": "Sydney Hurst",
  "date": "1977-10-22",
  "time": "23:22:00",
  "image": "https://server.appsstaging.com/3048/mao/mao/public/uploads/6259367672e50.jpg",
  "description": "Porro aliquam vitae",
  "address": "Temporibus quo cumqu",
  "images": [
    {
      "id": 13,
      "url": "https://server.appsstaging.com/3048/mao/mao/public/uploads/6259367672e50.jpg"
    }
  ],
  "sub": [
    {
      "title": "Sydney Hurst",
      "date": "1977-10-22",
      "time": "23:22:00"
    }
  ],
  "comments": [
    null
  ]
} 
*/

  int? id;
  String? title;
  String? date;
  String? time;
  String? image;
  String? description;
  String? address;
  List<NotificationModelDataDataImages?>? images;
  List<NotificationModelDataDataSub?>? sub;
  //List<NotificationModelDataDataComments?>? comments;

  NotificationModelDataData({
    this.id,
    this.title,
    this.date,
    this.time,
    this.image,
    this.description,
    this.address,
    this.images,
    this.sub,
    //this.comments,
  });
  NotificationModelDataData.fromJson(Map<dynamic, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    date = json['date']?.toString();
    time = json['time']?.toString();
    image = json['image']?.toString();
    description = json['description']?.toString();
    address = json['address']?.toString();
    if (json['images'] != null) {
      final v = json['images'];
      final arr0 = <NotificationModelDataDataImages>[];
      v.forEach((v) {
        arr0.add(NotificationModelDataDataImages.fromJson(v));
      });
      images = arr0;
    }
    if (json['sub'] != null) {
      final v = json['sub'];
      final arr0 = <NotificationModelDataDataSub>[];
      v.forEach((v) {
        arr0.add(NotificationModelDataDataSub.fromJson(v));
      });
      sub = arr0;
    }
    //>>>>>>error<<<<<<
  }
  Map<dynamic, dynamic> toJson() {
    final data = <dynamic, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['date'] = date;
    data['time'] = time;
    data['image'] = image;
    data['description'] = description;
    data['address'] = address;
    if (images != null) {
      final v = images;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['images'] = arr0;
    }
    if (sub != null) {
      final v = sub;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['sub'] = arr0;
    }
    //>>>>>>error<<<<<<
    return data;
  }
}

class NotificationModelData {
/*
{
  "id": 10,
  "sender_id": 2,
  "reciever_id": 14,
  "data": {
    "id": 16,
    "title": "Sydney Hurst",
    "date": "1977-10-22",
    "time": "23:22:00",
    "image": "https://server.appsstaging.com/3048/mao/mao/public/uploads/6259367672e50.jpg",
    "description": "Porro aliquam vitae",
    "address": "Temporibus quo cumqu",
    "images": [
      {
        "id": 13,
        "url": "https://server.appsstaging.com/3048/mao/mao/public/uploads/6259367672e50.jpg"
      }
    ],
    "sub": [
      {
        "title": "Sydney Hurst",
        "date": "1977-10-22",
        "time": "23:22:00"
      }
    ],
    "comments": [
      null
    ]
  },
  "type": "event",
  "created_at": "2022-04-15T09:10:14.000000Z",
  "updated_at": "2022-04-15T09:10:14.000000Z"
} 
*/

  int? id;
  int? senderId;
  int? recieverId;
  NotificationModelDataData? data;
  String? type;
  String? createdAt;
  String? updatedAt;

  NotificationModelData({
    this.id,
    this.senderId,
    this.recieverId,
    this.data,
    this.type,
    this.createdAt,
    this.updatedAt,
  });
  NotificationModelData.fromJson(Map<dynamic, dynamic> json) {
    id = json['id']?.toInt();
    senderId = json['sender_id']?.toInt();
    recieverId = json['reciever_id']?.toInt();
    data = (json['data'] != null)
        ? NotificationModelDataData.fromJson(json['data'])
        : null;
    type = json['type']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<dynamic, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['sender_id'] = senderId;
    data['reciever_id'] = recieverId;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['type'] = type;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class NotificationModel {
/*
{
  "status": 1,
  "data": [
    {
      "id": 10,
      "sender_id": 2,
      "reciever_id": 14,
      "data": {
        "id": 16,
        "title": "Sydney Hurst",
        "date": "1977-10-22",
        "time": "23:22:00",
        "image": "https://server.appsstaging.com/3048/mao/mao/public/uploads/6259367672e50.jpg",
        "description": "Porro aliquam vitae",
        "address": "Temporibus quo cumqu",
        "images": [
          {
            "id": 13,
            "url": "https://server.appsstaging.com/3048/mao/mao/public/uploads/6259367672e50.jpg"
          }
        ],
        "sub": [
          {
            "title": "Sydney Hurst",
            "date": "1977-10-22",
            "time": "23:22:00"
          }
        ],
        "comments": [
          null
        ]
      },
      "type": "event",
      "created_at": "2022-04-15T09:10:14.000000Z",
      "updated_at": "2022-04-15T09:10:14.000000Z"
    }
  ]
} 
*/

  int? status;
  List<NotificationModelData?>? data;

  NotificationModel({
    this.status,
    this.data,
  });
  NotificationModel.fromJson(Map<dynamic, dynamic> json) {
    status = json['status']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <NotificationModelData>[];
      v.forEach((v) {
        arr0.add(NotificationModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<dynamic, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}

class NotificationModel {
  final int? status;
  final List<Data>? data;

  NotificationModel({
    this.status,
    this.data,
  });

  NotificationModel.fromJson(Map<String, dynamic> json)
    : status = json['status'] as int?,
      data = (json['data'] as List?)?.map((dynamic e) => Data.fromJson(e as Map<String,dynamic>)).toList();

  Map<String, dynamic> toJson() => {
    'status' : status,
    'data' : data?.map((e) => e.toJson()).toList()
  };
}

class Data {
  final int? id;
  final int? senderId;
  final int? recieverId;
  final NData? data;
  final String? type;
  final String? createdAt;
  final String? updatedAt;

  Data({
    this.id,
    this.senderId,
    this.recieverId,
    this.data,
    this.type,
    this.createdAt,
    this.updatedAt,
  });

  Data.fromJson(Map<String, dynamic> json)
    : id = json['id'] as int?,
      senderId = json['sender_id'] as int?,
      recieverId = json['reciever_id'] as int?,
      data = (json['data'] as Map<String,dynamic>?) != null ? NData.fromJson(json['data'] as Map<String,dynamic>) : null,
      type = json['type'] as String?,
      createdAt = json['created_at'] as String?,
      updatedAt = json['updated_at'] as String?;

  Map<String, dynamic> toJson() => {
    'id' : id,
    'sender_id' : senderId,
    'reciever_id' : recieverId,
    'data' : data?.toJson(),
    'type' : type,
    'created_at' : createdAt,
    'updated_at' : updatedAt
  };
}

class NData {
  final int? id;
  final String? title;
  final String? date;
  final String? time;
  final String? image;
  final String? description;
  final String? address;
  final List<Images>? images;
  final List<Sub>? sub;
  final List<dynamic>? comments;

  NData({
    this.id,
    this.title,
    this.date,
    this.time,
    this.image,
    this.description,
    this.address,
    this.images,
    this.sub,
    this.comments,
  });

  NData.fromJson(Map<String, dynamic> json)
    : id = json['id'] as int?,
      title = json['title'] as String?,
      date = json['date'] as String?,
      time = json['time'] as String?,
      image = json['image'] as String?,
      description = json['description'] as String?,
      address = json['address'] as String?,
      images = (json['images'] as List?)?.map((dynamic e) => Images.fromJson(e as Map<String,dynamic>)).toList(),
      sub = (json['sub'] as List?)?.map((dynamic e) => Sub.fromJson(e as Map<String,dynamic>)).toList(),
      comments = json['comments'] as List?;

  Map<String, dynamic> toJson() => {
    'id' : id,
    'title' : title,
    'date' : date,
    'time' : time,
    'image' : image,
    'description' : description,
    'address' : address,
    'images' : images?.map((e) => e.toJson()).toList(),
    'sub' : sub?.map((e) => e.toJson()).toList(),
    'comments' : comments
  };
}

class Images {
  final int? id;
  final String? url;

  Images({
    this.id,
    this.url,
  });

  Images.fromJson(Map<String, dynamic> json)
    : id = json['id'] as int?,
      url = json['url'] as String?;

  Map<String, dynamic> toJson() => {
    'id' : id,
    'url' : url
  };
}

class Sub {
  final String? title;
  final String? date;
  final String? time;

  Sub({
    this.title,
    this.date,
    this.time,
  });

  Sub.fromJson(Map<String, dynamic> json)
    : title = json['title'] as String?,
      date = json['date'] as String?,
      time = json['time'] as String?;

  Map<String, dynamic> toJson() => {
    'title' : title,
    'date' : date,
    'time' : time
  };
}
*/
// class NotificationModel {
//   int? status;
//   List<NData>? data;

//   NotificationModel({this.status, this.data});

//   NotificationModel.fromJson(Map<String, dynamic> json) {
//     status = json['status'];
//     if (json['data'] != null) {
//       data = <NData>[];
//       json['data'].forEach((v) {
//         data!.add(new NData.fromJson(v));
//       });
//     }
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['status'] = this.status;
//     if (this.data != null) {
//       data['data'] = this.data!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }

// class NData {
//   int? id;
//   int? senderId;
//   int? recieverId;
//   Data? data;
//   String? type;
//   String? createdAt;
//   String? updatedAt;

//   NData(
//       {this.id,
//       this.senderId,
//       this.recieverId,
//       this.data,
//       this.type,
//       this.createdAt,
//       this.updatedAt});

//   NData.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     senderId = json['sender_id'];
//     recieverId = json['reciever_id'];
//     data = json['data'] != null ? new Data.fromJson(json['data']) : null;
//     type = json['type'];
//     createdAt = json['created_at'];
//     updatedAt = json['updated_at'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['sender_id'] = this.senderId;
//     data['reciever_id'] = this.recieverId;
//     if (this.data != null) {
//       data['data'] = this.data!.toJson();
//     }
//     data['type'] = this.type;
//     data['created_at'] = this.createdAt;
//     data['updated_at'] = this.updatedAt;
//     return data;
//   }
// }

// class Data {
//   int? id;
//   String? title;
//   String? date;
//   String? time;
//   String? image;
//   String? description;
//   String? address;
//   List<Images>? images;
//   List<Sub>? sub;
//   List<Null>? comments;

//   Data(
//       {this.id,
//       this.title,
//       this.date,
//       this.time,
//       this.image,
//       this.description,
//       this.address,
//       this.images,
//       this.sub,
//       this.comments});

//   Data.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     title = json['title'];
//     date = json['date'];
//     time = json['time'];
//     image = json['image'];
//     description = json['description'];
//     address = json['address'];
//     if (json['images'] != null) {
//       images = <Images>[];
//       json['images'].forEach((v) {
//         images!.add(new Images.fromJson(v));
//       });
//     }
//     if (json['sub'] != null) {
//       sub = <Sub>[];
//       json['sub'].forEach((v) {
//         sub!.add(new Sub.fromJson(v));
//       });
//     }
//     // if (json['comments'] != null) {
//     //   comments = <Null>[];
//     //   json['comments'].forEach((v) {
//     //     comments!.add(new Null.fromJson(v));
//     //   });
//     // }
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['title'] = this.title;
//     data['date'] = this.date;
//     data['time'] = this.time;
//     data['image'] = this.image;
//     data['description'] = this.description;
//     data['address'] = this.address;
//     if (this.images != null) {
//       data['images'] = this.images!.map((v) => v.toJson()).toList();
//     }
//     if (this.sub != null) {
//       data['sub'] = this.sub!.map((v) => v.toJson()).toList();
//     }
//     // if (this.comments != null) {
//     //   data['comments'] = this.comments!.map((v) => v.toJson()).toList();
//     // }
//     return data;
//   }
// }

// class Images {
//   int? id;
//   String? url;

//   Images({this.id, this.url});

//   Images.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     url = json['url'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['url'] = this.url;
//     return data;
//   }
// }

// class Sub {
//   String? title;
//   String? date;
//   String? time;

//   Sub({this.title, this.date, this.time});

//   Sub.fromJson(Map<String, dynamic> json) {
//     title = json['title'];
//     date = json['date'];
//     time = json['time'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['title'] = this.title;
//     data['date'] = this.date;
//     data['time'] = this.time;
//     return data;
//   }
// }
